# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
integration: !include integrations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
