# Loads default set of integrations. Do not remove.
default_config:

# homekit integration
homekit:
  filter:
    include_domains:
      - binary_sensor

# Example configuration.yaml entry
light:
  - platform: group
    name: group_714_lights_all
    entities:
      - light.0008dd898f1553
      #- light.neq1800641

cover:
  - platform: group
    name: group_714_cover_all
    entities:
      - cover.00115d8992e96b
      #- cover.00115d8992ea34

# Example configuration.yaml entry
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: "4161"
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

frontend:
  themes: !include themes.yaml
  javascript_version: latest
  #themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

# Telegram Bot Integration
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

automation: !include automations.yaml
homematic: !include integrations/homematic.yaml
tts: !include integrations/tts.yaml
#feedparser: !include integrations/rss.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
