- platform: feedparser
  name: Engineering Feed
  feed_url: "https://www.tvspielfilm.de/tv-programm/rss/jetzt.xml"
  date_format: "%a, %b %d %I:%M %p"
  scan_interval: 1

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

    #value must be one of ['date', 'date_time', 'date_time_iso', 'date_time_utc', 'time', 'time_date', 'time_utc'] 'display_options->7', got 'beat'

- platform: template
  sensors:
    # -------------------------------------------
    # CLIMATE Sensors
    # -------------------------------------------
    # climate_int0000001
    climate_int0000001_temperature:
      value_template: "{{ state_attr('climate.int0000001', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_int0000001_current_temperature:
      value_template: "{{ state_attr('climate.int0000001', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_int0000001_preset_mode:
      value_template: "{{ state_attr('climate.int0000001', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_int0000001_mode:
      value_template: "{{ state_attr('climate.int0000001', 'mode') }}"
      friendly_name: "Modus"

    # climate_int0000002
    climate_int0000002_temperature:
      value_template: "{{ state_attr('climate.int0000002', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_int0000002_current_temperature:
      value_template: "{{ state_attr('climate.int0000002', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_int0000002_preset_mode:
      value_template: "{{ state_attr('climate.int0000002', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_int0000002_mode:
      value_template: "{{ state_attr('climate.int0000002', 'mode') }}"
      friendly_name: "Modus"

    # climate_meq0182049
    climate_meq0182049_temperature:
      value_template: "{{ state_attr('climate.meq0182049', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_meq0182049_current_temperature:
      value_template: "{{ state_attr('climate.meq0182049', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_meq0182049_preset_mode:
      value_template: "{{ state_attr('climate.meq0182049', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_meq0182049_mode:
      value_template: "{{ state_attr('climate.meq0182049', 'mode') }}"
      friendly_name: "Modus"

    # climate.00265d89b11daa
    climate_00265d89b11daa_temperature:
      value_template: "{{ state_attr('climate.00265d89b11daa', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_00265d89b11daa_current_temperature:
      value_template: "{{ state_attr('climate.00265d89b11daa', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_00265d89b11daa_preset_mode:
      value_template: "{{ state_attr('climate.00265d89b11daa', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_00265d89b11daa_mode:
      value_template: "{{ state_attr('climate.00265d89b11daa', 'mode') }}"
      friendly_name: "Modus"

    # climate.meq0182083
    climate_meq0182083_temperature:
      value_template: "{{ state_attr('climate.meq0182083', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_meq0182083_current_temperature:
      value_template: "{{ state_attr('climate.meq0182083', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_meq0182083_preset_mode:
      value_template: "{{ state_attr('climate.meq0182083', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_meq0182083_mode:
      value_template: "{{ state_attr('climate.meq0182083', 'mode') }}"
      friendly_name: "Modus"

    # climate.meq0798691
    climate_meq0798691_temperature:
      value_template: "{{ state_attr('climate.meq0798691', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_meq0798691_current_temperature:
      value_template: "{{ state_attr('climate.meq0798691', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_meq0798691_preset_mode:
      value_template: "{{ state_attr('climate.meq0798691', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_meq0798691_mode:
      value_template: "{{ state_attr('climate.meq0798691', 'mode') }}"
      friendly_name: "Modus"

    # climate.meq0798800
    climate_meq0798800_temperature:
      value_template: "{{ state_attr('climate.meq0798800', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_meq0798800_current_temperature:
      value_template: "{{ state_attr('climate.meq0798800', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_meq0798800_preset_mode:
      value_template: "{{ state_attr('climate.meq0798800', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_meq0798800_mode:
      value_template: "{{ state_attr('climate.meq0798800', 'mode') }}"
      friendly_name: "Modus"

    # climate.oeq0659364
    climate_oeq0659364_temperature:
      value_template: "{{ state_attr('climate.oeq0659364', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_oeq0659364_current_temperature:
      value_template: "{{ state_attr('climate.oeq0659364', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_oeq0659364_preset_mode:
      value_template: "{{ state_attr('climate.oeq0659364', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_oeq0659364_mode:
      value_template: "{{ state_attr('climate.oeq0659364', 'mode') }}"
      friendly_name: "Modus"

    # climate.002a9d89bc211e
    climate_002a9d89bc211e_temperature:
      value_template: "{{ state_attr('climate.002a9d89bc211e', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_002a9d89bc211e_current_temperature:
      value_template: "{{ state_attr('climate.002a9d89bc211e', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_002a9d89bc211e_preset_mode:
      value_template: "{{ state_attr('climate.002a9d89bc211e', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_002a9d89bc211e_mode:
      value_template: "{{ state_attr('climate.002a9d89bc211e', 'mode') }}"
      friendly_name: "Modus"

    # climate.req0510046
    climate_req0510046_temperature:
      value_template: "{{ state_attr('climate.req0510046', 'temperature') | float }}"
      friendly_name: "Eingestellte Temperatur"
      unit_of_measurement: "°C"

    climate_req0510046_current_temperature:
      value_template: "{{ state_attr('climate.req0510046', 'current_temperature') | float }}"
      friendly_name: "Aktuelle Temperatur"
      unit_of_measurement: "°C"

    climate_req0510046_preset_mode:
      value_template: "{{ state_attr('climate.req0510046', 'preset_mode') }}"
      friendly_name: "Preset Modus"

    climate_req0510046_mode:
      value_template: "{{ state_attr('climate.req0510046', 'mode') }}"
      friendly_name: "Modus"

    # -------------------------------------------
    # LIGHT Sensors
    # -------------------------------------------
    # light.neq1800641
    light_neq1800641_supported_color_modes:
      value_template: "{{ state_attr('light.neq1800641', 'supported_color_modes') }}"
      friendly_name: "Supported Color Modes"

    light_neq1800641_color_mode:
      value_template: "{{ state_attr('light.neq1800641', 'color_mode') }}"
      friendly_name: "Color Mode"

    light_neq1800641_brightness:
      value_template: "{{ state_attr('light.neq1800641', 'brightness') | float }}"
      friendly_name: "Brightness"

    light_neq1800641_id:
      value_template: "{{ state_attr('light.neq1800641', 'id') }}"
      friendly_name: "ID"

    light_neq1800641_interface:
      value_template: "{{ state_attr('light.neq1800641', 'interface') }}"
      friendly_name: "Interface"

    light_neq1800641_level:
      value_template: "{{ state_attr('light.neq1800641', 'level') | float }}"
      friendly_name: "Level"

    light_neq1800641_working:
      value_template: "{{ state_attr('light.neq1800641', 'working') }}"
      friendly_name: "Working"

    light_neq1800641_friendly_name:
      value_template: "{{ state_attr('light.neq1800641', 'friendly_name') }}"
      friendly_name: "Friendly Name"

    light_neq1800641_supported_features:
      value_template: "{{ state_attr('light.neq1800641', 'supported_features') | float }}"
      friendly_name: "Supported Features"

    # light.0008dd898f1553
    light_0008dd898f1553_supported_color_modes:
      value_template: "{{ state_attr('light.0008dd898f1553', 'supported_color_modes') }}"
      friendly_name: "Supported Color Modes"

    light_0008dd898f1553_color_mode:
      value_template: "{{ state_attr('light.0008dd898f1553', 'color_mode') }}"
      friendly_name: "Color Mode"

    light_0008dd898f1553_brightness:
      value_template: "{{ state_attr('light.0008dd898f1553', 'brightness') | float }}"
      friendly_name: "Brightness"

    light_0008dd898f1553_id:
      value_template: "{{ state_attr('light.0008dd898f1553', 'id') }}"
      friendly_name: "ID"

    light_0008dd898f1553_interface:
      value_template: "{{ state_attr('light.0008dd898f1553', 'interface') }}"
      friendly_name: "Interface"

    light_0008dd898f1553_level:
      value_template: "{{ state_attr('light.0008dd898f1553', 'level') | float }}"
      friendly_name: "Level"

    light_0008dd898f1553_friendly_name:
      value_template: "{{ state_attr('light.0008dd898f1553', 'friendly_name') }}"
      friendly_name: "Friendly Name"

    light_0008dd898f1553_supported_features:
      value_template: "{{ state_attr('light.0008dd898f1553', 'supported_features') | float }}"
      friendly_name: "Supported Features"

    # -------------------------------------------
    # Homematic Sensors
    # -------------------------------------------
    # Abwesenheit

    # -------------------------------------------
    # Weather Sensors
    # -------------------------------------------
    sun_azimuth:
      friendly_name: "Sonnenwinkel"
      unit_of_measurement: "degrees"
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"

    weather_forecast:
      friendly_name: "Forecast Temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('weather.dwd_weather_diedorf_schwaben_bib', 'temperature') | float }}"
