- platform: template
  sensors:
    climate_int0000002_current_temperature:
      value_template: "{{ state_attr('climate.int0000002', 'temperature') | float }}"
      friendly_name: "Current Temperature"
      unit_of_measurement: "°C"
